# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.cache/wt [current_project]
set_property parent.project_path /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_output_repo /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG.xci
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_2/bd_178f_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_3/bd_178f_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_6/bd_178f_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_9/bd_178f_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_10/bd_178f_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/bd_178f_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_1/par/ddr4_MIG_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_board.xdc]
set_property used_in_implementation false [get_files -all /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/par/ddr4_MIG.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1 -new_name ddr4_MIG -ip [get_ips ddr4_MIG]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top ddr4_MIG -part xczu9eg-ffvb1156-2-e -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix ddr4_MIG_ ddr4_MIG.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ddr4_MIG_stub.v
 lappend ipCachedFiles ddr4_MIG_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ddr4_MIG_stub.vhdl
 lappend ipCachedFiles ddr4_MIG_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ddr4_MIG_sim_netlist.v
 lappend ipCachedFiles ddr4_MIG_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ddr4_MIG_sim_netlist.vhdl
 lappend ipCachedFiles ddr4_MIG_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp ddr4_MIG.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips ddr4_MIG]
}

rename_ref -prefix_all ddr4_MIG_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ddr4_MIG.dcp
create_report "ddr4_MIG_synth_1_synth_report_utilization_0" "report_utilization -file ddr4_MIG_utilization_synth.rpt -pb ddr4_MIG_utilization_synth.pb"

if { [catch {
  file copy -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1/ddr4_MIG.dcp /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1/ddr4_MIG.dcp /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1/ddr4_MIG_stub.v /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1/ddr4_MIG_stub.vhdl /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1/ddr4_MIG_sim_netlist.v /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.runs/ddr4_MIG_synth_1/ddr4_MIG_sim_netlist.vhdl /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.ip_user_files/ip/ddr4_MIG]} {
  catch { 
    file copy -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_stub.v /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.ip_user_files/ip/ddr4_MIG
  }
}

if {[file isdir /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.ip_user_files/ip/ddr4_MIG]} {
  catch { 
    file copy -force /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_stub.vhdl /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.ip_user_files/ip/ddr4_MIG
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
