# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG.xci
# IP: The module: 'ddr4_MIG' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_MIG_microblaze_mcs || ORIG_REF_NAME==ddr4_MIG_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/bd_178f.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f || ORIG_REF_NAME==bd_178f} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_microblaze_I_0 || ORIG_REF_NAME==bd_178f_microblaze_I_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_rst_0_0 || ORIG_REF_NAME==bd_178f_rst_0_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_2/bd_178f_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_ilmb_0 || ORIG_REF_NAME==bd_178f_ilmb_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_3/bd_178f_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_dlmb_0 || ORIG_REF_NAME==bd_178f_dlmb_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_4/bd_178f_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_178f_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_5/bd_178f_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_178f_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_6/bd_178f_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_lmb_bram_I_0 || ORIG_REF_NAME==bd_178f_lmb_bram_I_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_7/bd_178f_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_178f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_8/bd_178f_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_178f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_9/bd_178f_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_178f_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_10/bd_178f_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_iomodule_0_0 || ORIG_REF_NAME==bd_178f_iomodule_0_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_1/ddr4_MIG_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_MIG_phy || ORIG_REF_NAME==ddr4_MIG_phy} -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_microblaze_I_0 || ORIG_REF_NAME==bd_178f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0_ooc_debug.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_rst_0_0 || ORIG_REF_NAME==bd_178f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_rst_0_0 || ORIG_REF_NAME==bd_178f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_2/bd_178f_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_ilmb_0 || ORIG_REF_NAME==bd_178f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_3/bd_178f_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_dlmb_0 || ORIG_REF_NAME==bd_178f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_6/bd_178f_lmb_bram_I_0_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_9/bd_178f_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_10/bd_178f_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_iomodule_0_0 || ORIG_REF_NAME==bd_178f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/bd_178f_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_MIG_microblaze_mcs || ORIG_REF_NAME==ddr4_MIG_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_1/par/ddr4_MIG_phy_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_MIG'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/par/ddr4_MIG.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_MIG'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG.xci
# IP: The module: 'ddr4_MIG' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_MIG_microblaze_mcs || ORIG_REF_NAME==ddr4_MIG_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/bd_178f.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f || ORIG_REF_NAME==bd_178f} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_microblaze_I_0 || ORIG_REF_NAME==bd_178f_microblaze_I_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_rst_0_0 || ORIG_REF_NAME==bd_178f_rst_0_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_2/bd_178f_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_ilmb_0 || ORIG_REF_NAME==bd_178f_ilmb_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_3/bd_178f_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_dlmb_0 || ORIG_REF_NAME==bd_178f_dlmb_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_4/bd_178f_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_dlmb_cntlr_0 || ORIG_REF_NAME==bd_178f_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_5/bd_178f_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_ilmb_cntlr_0 || ORIG_REF_NAME==bd_178f_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_6/bd_178f_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_lmb_bram_I_0 || ORIG_REF_NAME==bd_178f_lmb_bram_I_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_7/bd_178f_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_178f_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_8/bd_178f_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_178f_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_9/bd_178f_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_178f_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_10/bd_178f_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_178f_iomodule_0_0 || ORIG_REF_NAME==bd_178f_iomodule_0_0} -quiet] -quiet

# IP: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_1/ddr4_MIG_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_MIG_phy || ORIG_REF_NAME==ddr4_MIG_phy} -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_microblaze_I_0 || ORIG_REF_NAME==bd_178f_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_0/bd_178f_microblaze_I_0_ooc_debug.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_rst_0_0 || ORIG_REF_NAME==bd_178f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_1/bd_178f_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_rst_0_0 || ORIG_REF_NAME==bd_178f_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_2/bd_178f_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_ilmb_0 || ORIG_REF_NAME==bd_178f_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_3/bd_178f_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_dlmb_0 || ORIG_REF_NAME==bd_178f_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_6/bd_178f_lmb_bram_I_0_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_9/bd_178f_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/ip/ip_10/bd_178f_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_178f_iomodule_0_0 || ORIG_REF_NAME==bd_178f_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/bd_0/bd_178f_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_MIG_microblaze_mcs || ORIG_REF_NAME==ddr4_MIG_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_0/ddr4_MIG_microblaze_mcs_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ip_1/par/ddr4_MIG_phy_ooc.xdc

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/ddr4_MIG_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_MIG'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/user/Work/UCMerced/cva6_ddr4/corev_apu/fpga/xilinx/ddr4_MIG/ddr4_MIG.srcs/sources_1/ip/ddr4_MIG/par/ddr4_MIG.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_MIG'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
